/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServerErrorRouteImport } from './routes/server-error'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DonateCallbackRouteImport } from './routes/donate.callback'
import { Route as DonateSlugRouteImport } from './routes/donate.$slug'
import { Route as CampaignsSlugRouteImport } from './routes/campaigns.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminCampaignsIdRouteImport } from './routes/admin.campaigns.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerErrorRoute = ServerErrorRouteImport.update({
  id: '/server-error',
  path: '/server-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DonateCallbackRoute = DonateCallbackRouteImport.update({
  id: '/donate/callback',
  path: '/donate/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateSlugRoute = DonateSlugRouteImport.update({
  id: '/donate/$slug',
  path: '/donate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugRoute = CampaignsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CampaignsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsIdRoute = AdminCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/campaigns': typeof CampaignsRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/server-error': typeof ServerErrorRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/users': typeof AdminUsersRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/donate/callback': typeof DonateCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/admin/campaigns/$id': typeof AdminCampaignsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/change-password': typeof ChangePasswordRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/server-error': typeof ServerErrorRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/users': typeof AdminUsersRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/donate/callback': typeof DonateCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/admin/campaigns/$id': typeof AdminCampaignsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/campaigns': typeof CampaignsRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/server-error': typeof ServerErrorRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/users': typeof AdminUsersRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/donate/callback': typeof DonateCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/admin/campaigns/$id': typeof AdminCampaignsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/campaigns'
    | '/change-password'
    | '/create'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/server-error'
    | '/signup'
    | '/unauthorized'
    | '/admin/users'
    | '/campaigns/$slug'
    | '/donate/$slug'
    | '/donate/callback'
    | '/admin/'
    | '/campaigns/'
    | '/admin/campaigns/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/change-password'
    | '/create'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/server-error'
    | '/signup'
    | '/unauthorized'
    | '/admin/users'
    | '/campaigns/$slug'
    | '/donate/$slug'
    | '/donate/callback'
    | '/admin'
    | '/campaigns'
    | '/admin/campaigns/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/campaigns'
    | '/change-password'
    | '/create'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/server-error'
    | '/signup'
    | '/unauthorized'
    | '/admin/users'
    | '/campaigns/$slug'
    | '/donate/$slug'
    | '/donate/callback'
    | '/admin/'
    | '/campaigns/'
    | '/admin/campaigns/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CampaignsRoute: typeof CampaignsRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServerErrorRoute: typeof ServerErrorRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  DonateSlugRoute: typeof DonateSlugRoute
  DonateCallbackRoute: typeof DonateCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-error': {
      id: '/server-error'
      path: '/server-error'
      fullPath: '/server-error'
      preLoaderRoute: typeof ServerErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/donate/callback': {
      id: '/donate/callback'
      path: '/donate/callback'
      fullPath: '/donate/callback'
      preLoaderRoute: typeof DonateCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/$slug': {
      id: '/donate/$slug'
      path: '/donate/$slug'
      fullPath: '/donate/$slug'
      preLoaderRoute: typeof DonateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug': {
      id: '/campaigns/$slug'
      path: '/$slug'
      fullPath: '/campaigns/$slug'
      preLoaderRoute: typeof CampaignsSlugRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns/$id': {
      id: '/admin/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/admin/campaigns/$id'
      preLoaderRoute: typeof AdminCampaignsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCampaignsIdRoute: typeof AdminCampaignsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCampaignsIdRoute: AdminCampaignsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CampaignsRouteChildren {
  CampaignsSlugRoute: typeof CampaignsSlugRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsSlugRoute: CampaignsSlugRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CampaignsRoute: CampaignsRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServerErrorRoute: ServerErrorRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  DonateSlugRoute: DonateSlugRoute,
  DonateCallbackRoute: DonateCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
